- readme.txt
Updated readme file with the stable version
> Chore: Updated readme file with stable version

- ph-child.php
- readme.txt
https://d.pr/wHo8Y1
**Improvement**
> Allow guests (allow guest to comment) checkbox field changes.

- ph-child.php
- readme.txt
A help link is added for manual installation instruction with Manual installation docs.
https://d.pr/v/Et1TbT
Improvement
> Help link added for Detailed instruction on How to connect the site manually?

- ph-child.php
- readme.txt
**Ticket -** 
https://secure.helpscout.net/conversation/1851476115/176483?folderId=5252892
The user gets confused about this option, they are considering this option is for adding comments by using that user role from the client site.
https://share.getcloudapp.com/5zuLOwRy
improvement
> Comment access settings options changes.

- package.json
- ph-child.php
- readme.txt
* Improvement: Compatibility to WordPress 6.0.
* Improvement: Help link added for detailed instructions of site connection.
* Improvement: Comment access settings description and label changes.
NA
Improvement
> Version 1.0.32

- package.json
- ph-child.php
- readme.txt
Updated WordPress compatibility tag
NA
Improvement
NA
> Updated WordPress compatibility tag

- package.json
- ph-child.php
- readme.txt
== Changelog ==
= 1.0.33 =
* Improvement: Compatibility to WordPress 6.0.2
> Chore: Version 1.0.33

- ph-child.php
- readme.txt
- No issues found
- Updated Tested Upto tag
> WordPress 6.2 compatibility

- ph-child.php
> Reverted changes in ph-child.php

- ph-child.php
- readme.txt
Updated Wordpress version to 6.3
> EPS-223 Updated Wordpress version to 6.3

- package.json
- ph-child.php
- readme.txt
* Improvement: Compatibility to WordPress 6.3
> EPS-223 Version 1.0.34

- package.json
- ph-child-functions.php
- ph-child.php
- readme.txt
Improvement: Implemented nonce verification and data sanitization to enhance security.
> Version 1.0.35

- composer.json
- package.json
- ph-child-functions.php
- ph-child.php
- readme.txt
- uninstall.php
Rebranding ProjectHuddle as SureFeedback.
> Version 1.1

- ph-child.php
- readme.txt
> Version 1.2 

- ph-child.php
- readme.txt
> EPS-464 WordPress 6.5 version compatibility

- ph-child.php
- readme.txt
> Version 1.2.2

- ph-child-functions.php
- ph-child.php
- readme.txt
* Improvement: Updated help document links.
> Version 1.2.3

- ph-child-functions.php
- ph-child.php
- readme.txt
Improvement: Compatibility to WordPress 6.6
> Build 1.2.4

- .github/workflows/push-to-deploy.yml
> Push to deploy.yml file changes

- ph-child.php
> Reverted version number in main file

- package.json
- ph-child.php
- readme.txt
> Updated readme file

- ph-child.php
- readme.txt
> Version Update 6.8

- package.json
- ph-child.php
- readme.txt
> Compatibility with WP 6.8

- ph-child-rest-api.php
- ph-child.php
> Enabling comments widget on specific pages in word press

- readme.txt
…enhance CORS policy, and implement security fixes
[BSF-PR-SUMMARY]
> Update changelog remove vulnerabilities line

- ph-child-rest-api.php
- ph-child.php
- readme.txt
> Fixed empty OPTIONS responses from WordPress/WooCommerce REST APIs to restore Zapier and integration compatibility.
